/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buoi5.model.view;


import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author HP
 */
public class jsliderJFrame extends javax.swing.JFrame {

    /**
     * Creates new form jsliderJFrame
     */
    public jsliderJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        Hashtable data = new Hashtable();
        String[] months = {"Jan", "Fed", "Mar", "Apr", "May", "Jun",
            "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        for (int i = 0; i < 12; i++) {
            data.put(i, new JLabel(months[i]));
        }
        sdlmonth.setLabelTable(data);
        Calendar can = Calendar.getInstance();
        sldDay.setValue(can.get(Calendar.DAY_OF_MONTH));
        sdlmonth.setValue(can.get(Calendar.MONTH));
        sdlyear.setValue(can.get(Calendar.YEAR));
        displaydata();
    }
    public void displaydata(){
        SimpleDateFormat sdf = new SimpleDateFormat("EEE,dd-MMM-YYYY");
        int dd = sldDay.getValue();
        int mm = sdlmonth.getValue() ;
        int yy = sdlyear.getValue()-1900;
        Date d = new Date(yy, mm, dd);
        lbi.setText(sdf.format(d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldDay = new javax.swing.JSlider();
        sdlyear = new javax.swing.JSlider();
        sdlmonth = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        lbi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sldDay.setBackground(new java.awt.Color(102, 102, 255));
        sldDay.setMajorTickSpacing(5);
        sldDay.setMaximum(31);
        sldDay.setMinimum(1);
        sldDay.setMinorTickSpacing(1);
        sldDay.setPaintLabels(true);
        sldDay.setPaintTicks(true);
        sldDay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDayStateChanged(evt);
            }
        });

        sdlyear.setBackground(new java.awt.Color(255, 255, 51));
        sdlyear.setMajorTickSpacing(5);
        sdlyear.setMaximum(2020);
        sdlyear.setMinimum(2000);
        sdlyear.setPaintLabels(true);
        sdlyear.setPaintTicks(true);
        sdlyear.setValue(2010);
        sdlyear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdlyearStateChanged(evt);
            }
        });

        sdlmonth.setBackground(new java.awt.Color(153, 255, 255));
        sdlmonth.setMajorTickSpacing(1);
        sdlmonth.setMaximum(11);
        sdlmonth.setMinorTickSpacing(1);
        sdlmonth.setPaintLabels(true);
        sdlmonth.setPaintTicks(true);
        sdlmonth.setToolTipText("");
        sdlmonth.setValue(4);
        sdlmonth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdlmonthStateChanged(evt);
            }
        });

        jLabel1.setText("day");
        jLabel1.setOpaque(true);

        lbi.setText("hiện");

        jLabel3.setText("year");

        jLabel4.setText("month");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbi)
                    .addComponent(sldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdlmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdlyear, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sdlmonth, sdlyear, sldDay});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(sldDay, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sdlmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sdlyear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(lbi)
                .addGap(102, 102, 102))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {sdlmonth, sdlyear, sldDay});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldDayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDayStateChanged
      
        if(sldDay.getValueIsAdjusting()){
            return;
        }
          displaydata();
    }//GEN-LAST:event_sldDayStateChanged

    private void sdlmonthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdlmonthStateChanged
  
         if(sdlmonth.getValueIsAdjusting()){
            return;
        }
              displaydata(); 
    }//GEN-LAST:event_sdlmonthStateChanged

    private void sdlyearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdlyearStateChanged
    
        if(sdlyear.getValueIsAdjusting()){
            return;
        }
          displaydata(); 
    }//GEN-LAST:event_sdlyearStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jsliderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jsliderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jsliderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jsliderJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jsliderJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbi;
    private javax.swing.JSlider sdlmonth;
    private javax.swing.JSlider sdlyear;
    private javax.swing.JSlider sldDay;
    // End of variables declaration//GEN-END:variables
}
